---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mco-report
  namespace: mco-report-web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mco-report
  template:
    metadata:
      labels:
        app: mco-report
    spec:
      containers:
        - name: mco-report
          image: __ACR__/bca/mco-report:__GITHASH__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 15"]

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mco-report-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2 # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mco-report
  targetCPUUtilizationPercentage: 70 # target CPU utilization

---
apiVersion: v1
kind: Service
metadata:
  name: mco-report
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: mco-report
